// Code generated by Object Plant

#include	"FTGLOutlineFont.h"
#include	"FTGlyphContainer.h"
#include	"FTGL.h"


FTGLOutlineFont::FTGLOutlineFont()
//Insert your own initialization here.

//End of user initialization.         
{
//Insert your own code here.

//End of user code.         
}


FTGLOutlineFont::~FTGLOutlineFont()
{
//Insert your own code here.

//End of user code.         
}

