// Code generated by Object Plant

#include	"FTSize.h"
#include	"FTGL.h"
//Insert your own code here.

//End of user code.         

// OPSignature:  FTSize:FTSize() 
FTSize::FTSize()
:	size(0)
{
//Insert your own code here.

//End of user code.         
}


// OPSignature:  FTSize:~FTSize() 
FTSize::~FTSize()
{
//Insert your own code here.

//End of user code.         
}


// OPSignature: bool FTSize:SetCharSize( FT_Face:face  int:point_size  int:x_resolution  int:y_resolution ) 
bool	FTSize::CharSize( FT_Face* face, int point_size, int x_resolution, int y_resolution )
{
	size = point_size;
	FT_Error err = FT_Set_Char_Size( *face, 0L, point_size * 64, x_resolution, y_resolution);

	return !err;
}


// OPSignature: int FTSize:GetAscender() 
int	FTSize::Ascender() const
{
//Insert your own code here.

//End of user code.         
}


// OPSignature: int FTSize:GetDescender() 
int	FTSize::Descender() const
{
//Insert your own code here.

//End of user code.         
}
