// Code generated by Object Plant

#include	"FTSize.h"
#include	"FTGL.h"
//Insert your own code here.

//End of user code.         

// OPSignature:  FTSize:FTSize() 
FTSize::FTSize()
:	size(0)
{
//Insert your own code here.

//End of user code.         
}


// OPSignature:  FTSize:~FTSize() 
FTSize::~FTSize()
{
//Insert your own code here.

//End of user code.         
}


// OPSignature: bool FTSize:SetCharSize( FT_Face:face  int:point_size  int:x_resolution  int:y_resolution ) 
bool	FTSize::CharSize( FT_Face* ftFace, int point_size, int x_resolution, int y_resolution )
{
	size = point_size;
	FT_Error err = FT_Set_Char_Size( *ftFace, 0L, point_size * 64, x_resolution, y_resolution);
	
	ftSize = (*ftFace)->size;
	
	return !err;
}


// OPSignature: int FTSize:GetAscender() 
int	FTSize::Ascender() const
{
	return ftSize->metrics.ascender;
}


// OPSignature: int FTSize:GetDescender() 
int	FTSize::Descender() const
{
	return ftSize->metrics.descender;
}


// OPSignature: int FTSize:Height() 
int	FTSize::Height() const
{
	return ftSize->metrics.height;
}


// OPSignature: int FTSize:Width() 
int	FTSize::Width() const
{
	return ftSize->metrics.max_advance;
}
